markdown: redcarpet
highlighter: pygments
permalink: /:year-:month-:day/:title.html

url: mindspop.github.io
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed